package com.dreamhomes.haven.dreamai.turn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;

/**
 * Per-listing reasoning attached to a {@code compare}-kind turn. The frontend renders
 * this alongside the listing card so the AI's case for each option is visible at a
 * glance — pros, cons, and a "best for" persona one-liner.
 *
 * <p>Generated by {@link com.dreamhomes.haven.dreamai.client.AnthropicListingCompareClient}.
 * The model is constrained (system prompt) to only use ids that appear in the request,
 * and the orchestrator drops any note whose id isn't in the validated LIVE set.</p>
 */
@Schema(description = "AI-generated comparison notes for one listing.")
public record PerListingNote(
        @Schema(description = "Listing id this note describes.", example = "12")
        Long id,

        @Schema(description = "Short headline summarising the listing's character (max ~80 chars).",
                example = "Top-floor 3-bed with sea-view balcony")
        String headline,

        @Schema(description = "Concrete advantages — features, location signals, price wins.")
        List<String> pros,

        @Schema(description = "Honest drawbacks — fees, distance, fit gaps.")
        List<String> cons,

        @Schema(description = "One-line persona this listing fits best.",
                example = "A young professional couple who want sea-view weekends and a short Lekki commute.")
        String bestFor
) {
    @JsonCreator
    public PerListingNote(
            @JsonProperty("id") Long id,
            @JsonProperty("headline") String headline,
            @JsonProperty("pros") List<String> pros,
            @JsonProperty("cons") List<String> cons,
            @JsonProperty("bestFor") String bestFor) {
        this.id = id;
        this.headline = headline;
        this.pros = pros == null ? List.of() : List.copyOf(pros);
        this.cons = cons == null ? List.of() : List.copyOf(cons);
        this.bestFor = bestFor;
    }
}
