spring.application.name=dreamhomes-haven
spring.datasource.url=jdbc:postgresql://localhost:5432/dreamhomes_haven
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

jwt.expiration-ms=3600000