spring.application.name=dreamhomes-haven
spring.datasource.url=jdbc:postgresql://localhost:5432/haven_db
spring.datasource.username=haven_user
spring.datasource.password=haven_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true


server.port=8080

jwt.expiration-ms=3600000


