apiVersion: apps/v1
kind: Deployment
metadata:
  name: haven-api
  namespace: haven
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: haven-api
  template:
    metadata:
      labels:
        app: haven-api
    spec:
      containers:
        - name: haven-api
          image: 968306633089.dkr.ecr.us-east-1.amazonaws.com/haven:manual
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: haven-config
            - secretRef:
                name: haven-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              cpu: 250m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 768Mi
